# Generated by Django 4.1.5 on 2023-02-13 01:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simpleapp', '0003_alter_articles_description_alter_news_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='description',
            field=models.TextField(default='Ваша статья', verbose_name='Содержание'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='news',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='news',
            name='description',
            field=models.TextField(default='Ваша новость', verbose_name='Содержание'),
        ),
        migrations.AlterField(
            model_name='news',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Заголовок'),
        ),
    ]
